# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
    CLOUD_SQL_USERNAME: adproject
    CLOUD_SQL_PASSWORD: 1234
    CLOUD_SQL_DATABASE_NAME: demo
    CLOUD_SQL_CONNECTION_NAME: webtemplate-366211:europe-west2:adproject
# [END gae_python37_cloudsql_config]